SET FOREIGN_KEY_CHECKS=0; DROP DATABASE IF EXISTS gamezone_store; CREATE DATABASE gamezone_store CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; USE gamezone_store; SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE usuarios (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL,correo VARCHAR(150) NOT NULL UNIQUE,clave VARCHAR(255) NOT NULL,rol ENUM('superadmin','admin','usuario') NOT NULL DEFAULT 'usuario',email_verificado TINYINT(1) NOT NULL DEFAULT 0,codigo_verificacion VARCHAR(10) NULL,codigo_expira DATETIME NULL,foto_perfil VARCHAR(500) NULL,creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE juegos (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(150) NOT NULL,descripcion TEXT NOT NULL,precio DECIMAL(10,2) NOT NULL,imagen VARCHAR(500) NOT NULL,categoria VARCHAR(30) NOT NULL,slug VARCHAR(120) NOT NULL UNIQUE,creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

INSERT INTO usuarios (nombre,correo,clave,rol,email_verificado) VALUES
('Super Administrador','superadmin@gamezone.com','$2y$12$uMVB3RYsUzYH4iNhkJ0fLOM9vu63wC/wKS2bPa8w98sTRRJwL4olS','superadmin',1),
('Administrador','admin@gamezone.com','$2y$12$j7XTXp/YWRrDw.2K3Ub0o.OItUzdIlEWiASV964KgNU1l7ArD8GMq','admin',1),
('Usuario','usuario@gamezone.com','$2y$12$kXa9uOdCUIM0pee/U/xp/uiH6s9ep.siNYqcCgJmlLCONDwGoCZLK','usuario',1);

INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Elden Ring','Descripción del producto ELDEN RING es un juego de rol de acción desarrollado por FromSoftware, conocido por su trabajo en la serie Dark Souls. El juego presenta un mundo abierto y una narrativa profunda, con elementos de exploración y combate característicos de los títulos anteriores del estudio. Los jugadores asumen el papel de un personaje conocido como el "Tarnished", que busca restaurar el Elden Ring y convertirse en el Elden Lord. Con un diseño artístico impresionante y una jugabilidad desafiante, ELDEN RING ofrece una experiencia inmersiva en un mundo lleno de misterios y peligros. Los jugadores pueden personalizar su personaje, elegir entre diferentes clases y habilidades, y enfrentarse a enemigos temibles en su búsqueda por desentrañar los secretos del Elden Ring.',59.90,'assets/juegos-ps5/Elden-ring.webp','PS5','eldenring');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Nba2k25','Descripción del Producto Juego mejorado: siéntete como un profesional de la NBA con una jugabilidad mejorada y autenticidad elevada. Experimenta los movimientos característicos de tus jugadores favoritos de la NBA y afina tus habilidades para ofrecer jugadas que definan tu carrera de manera dramática. Míralos cobrar vida con imágenes impresionantes, movimientos genuinos y modos de juego inmersivos.
            Posee el vecindario - Bienvenido al vecindario, una jungla de concreto completamente nueva donde el aro y la ganancia es todo lo que cuenta. Marca el comienzo de la dinastía más grande que la liga haya visto en MyCARRERA mientras te elevas a la grandeza. Completa misiones, gana recompensas y eclipsa a tus rivales en modos de juego nuevos y regresantes mientras grabas tu nombre entre los grandes.',59.90,'assets/juegos-ps5/nba2k25.webp','PS5','nba2k25');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Resident Evil 4','Descripción del Producto Resident Evil 4 conserva la esencia del juego original, ahora reconstruido utilizando el RE Engine patentado de Capcom para ofrecer imágenes realistas y profundidad narrativa adicional a la historia icónica que no era posible en el momento del lanzamiento original.
        Juego modernizado: el equipo de Resident Evil 2 de 2019 regresa para construir sobre el enfoque moderno de la serie para el terror de supervivencia. Participa en un combate frenético con los aldeanos de Ganados, explora un pueblo europeo atrapado por la locura, y resuelve acertijos para acceder a nuevas áreas y recoger objetos útiles para la constante lucha de Leon y Ashley por sobrevivir.
        Hordas abrumadoras: enfréntate a hordas de enemigos rabiosos que amenazan con abrumar a León con métodos de ataque aún más diversos que en la versión original.',39.90,'assets/juegos-ps5/re4.webp','PS5','re4');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Mortal Kombat 1','Descripción del Producto Un Nuevo Universo - Descubre un nuevo comienzo, creado por el Guardián del Tiempo y protector de Earthrealm, Dios del Fuego Liu Kang.
            Origins Reimagined - Los personajes familiares regresan con todas las nuevas historias entrelazadas, interactuando de formas completamente nuevas.
            Nuevos Kameo Fighters - Elige entre una lista única de compañeros de combate Kameo para ayudarte en la batalla.
            Campaña de historia inmersiva: lucha a través de una nueva historia con tus personajes favoritos de Mortal Kombat como nunca los has visto antes.
            Vuelve la franquicia Ultimate Fighting - The Fight for Earthrealm está sobre nosotros. Este es Mortal Kombat.
            Algunas funciones pueden requerir una conexión a Internet y una suscripción en línea.',59.90,'assets/juegos-ps5/mk1.webp','PS5','mk1');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('The Last of Us II','Descripción del Producto Mejoras para PS5 de Natie - Construido para PS5, The Last of Us Part II Remastered mejora el juego original de PS4 de formas que antes no eran posibles.
            Sin retorno – Un modo de supervivencia Roguelike – ¡Experimenta el profundo combate de The Last of Us Part II a través de un modo completamente nuevo! Sobrevive todo el tiempo que puedas en cada carrera, mientras eliges tu camino a través de una serie de encuentros aleatorios con diferentes enemigos y lugares memorables de toda la Parte II, todo culminando en tensas batallas de jefes.
            Nuevas formas de jugar: profundiza en esta querida aventura y aprende cómo se creó el juego original.
            Mejoras gráficas: The Last of Us Part II Remastered presenta un rendimiento nativo de 4K* en el modo Fidelity, mejoras en la velocidad de fotogramas y admite velocidad de actualización variable',59.90,'assets/juegos-ps5/tlou.webp','PS5','tlou2');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Dark Souls III','Descripción del producto Visuales atmosféricos: La iluminación dinámica y los efectos de partículas sumergen a los jugadores en un oscuro mundo de fantasía de ruina.
            Mundo interconectado: El mundo diseñado por expertos anima a los jugadores a explorar paisajes vastos e impresionantes.
            Acción de espada: Diversifica la acción de combate permitiendo a los jugadores crear su propio estilo de juego único.
            Sistema único en línea: Evolución de la funcionalidad multijugador en línea de marca registrada que integra perfectamente las interacciones en línea en la historia de un solo jugador.
            Forma equipo para una buena cooperación alegre o prueba tu habilidad en la batalla PvP: Todos los mapas PvP desbloqueados y accesibles. Mejora en línea casamentero funcionalidad.',59.90,'assets/juegos-ps4/darksouls3.webp','PS4','darksouls3');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Dragon Ball FighterZ','Descripción del producto Visuales atmosféricos: La iluminación dinámica y los efectos de partículas sumergen a los jugadores en un oscuro mundo de fantasía de ruina.
            Mundo interconectado: El mundo diseñado por expertos anima a los jugadores a explorar paisajes vastos e impresionantes.
            Acción de espada: Diversifica la acción de combate permitiendo a los jugadores crear su propio estilo de juego único.
            Sistema único en línea: Evolución de la funcionalidad multijugador en línea de marca registrada que integra perfectamente las interacciones en línea en la historia de un solo jugador.
            Forma equipo para una buena cooperación alegre o prueba tu habilidad en la batalla PvP: Todos los mapas PvP desbloqueados y accesibles. Mejora en línea casamentero funcionalidad.',37.90,'assets/juegos-ps4/dbzfighterz.webp','PS4','dbzfighterz');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Mortal Kombat 11','Descripción del producto Experimenta 2 campañas de historias sólidas y aclamadas por la crítica de Mk11 y Mk11: consecuencias
            Juega como la lista completa de 37 personajes, incluyendo a los luchadores recién agregados Mileena, RaiN y Rambo
            Miles de Skins & Weapons & Gear para un nivel sin precedentes de personalización Fighter
            Incluye a todos los luchadores invitados anteriores, como Terminator Joker engendros y Robocop
            Todos los modos incluidos, la experiencia definitiva mk11! Toma el control de los protectores de earthrealm, en las dos campañas de historias aclamadas por la crítica mientras corren para evitar que Kronika rebobine el tiempo y reinicie la historia.
            Se ponen a prueba las amistades y se forjan nuevas alianzas en la batalla por salvar toda la existencia. mk11 ultimate presenta la lista completa de personajes, ',35.90,'assets/juegos-ps4/mk11.webp','PS4','mk11');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Street Fighter 6','Descripción del producto Experiencia clásica diseñada para una era moderna: con todos los modos de juego principales presentes, además de dos nuevos modos y imágenes mejoradas, Street Fighter 6 redefine el género clásico de juegos de lucha.
            Estilos de lucha distintos para dominar: 18 personajes diversos, incluidos los legendarios World Warriors y emocionantes personajes nuevos, agregan su propio estilo al juego en el lanzamiento, y más se agregarán después del lanzamiento.
            Nuevos modos de juego: La franquicia Street Fighter continúa perfeccionando sus habilidades y redefiniendo el género de lucha con la introducción de tres nuevos modos fundamentales: Fighting Ground, World Tour y Battle Hub.
            Comentarios en el juego: La primera función de comentarios en tiempo real de Street Fighter, compatible con subtítulos en 13 idiomas, incorpora las voces de co',69.90,'assets/juegos-ps4/streetfighter6.webp','PS4','streetfighter6');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('The Crew MotorFest','Descripción del producto Explora un vibrante mundo abierto hawaiano. El Crew Motorfest se ha establecido en uno de los lugares más impresionantes de la Tierra: la isla de O''ahu, Hawai. Únete a carreras callejeras de alta velocidad por la bulliciosa ciudad de Honolulu, prueba tus habilidades fuera de la carretera en las laderas cenicientas de un volcán, o domina la curva perfecta en las pistas
            Celebra todas las facetas de la cultura del automóvil. ¡Disfruta de una variedad de emocionantes actividades de conducción y elige cómo quieres divertirte con tus coches! ¡Descubre las listas de reproducción y sumérgete en campañas temáticas que te sumergirán en los universos de la cultura automotriz más emocionantes, incluyendo el músculo estadounidense, las carreras callejeras de estilo japonés y las máquinas legendarias del pasado!
            Colecciona los coches más legendarios. ',49.90,'assets/juegos-ps4/thecrew.webp','PS4','thecrew');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Animal Crossing','Descripción del producto Construye tu comunidad desde cero en una isla desierta repleta de posibilidades; crea tu escapada personal y personaliza tu personaje, hogar, decoraciones e incluso el propio paisaje
            Colecciona materiales para construir todo, desde muebles hasta herramientas. A continuación, utiliza lo que creas para dar a tu isla un toque personal
            Mira como la hora del día y las estaciones coinciden con la vida real, incluso con tu hemisferio. Cada día tiene potencial para sorpresas y descubrimientos
            Conoce a los residentes de la isla, jardín, pescado, decora, caza de fósiles, y mucho más.
            Muestra tu paraíso – Juega en el mismo sistema con un total de 4 personas, o juega juntos en línea o sobre inalámbrico local para diversión con hasta 8 jugadores',59.90,'assets/juegos-switch/animalcrossing.webp','Switch','animalcrossing');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Mario Kart 8 Deluxe','Descripción del Producto ¡Sal a la carretera con la versión definitiva de Mario Kart 8 y juega en cualquier momento y en cualquier lugar! Compite con tus amigos o lucha contra ellos en un modo de batalla revisado en cursos de batalla nuevos y regresantes
            Juega localmente en multijugador de hasta 4 jugadores en 1080p mientras juegas en modo TV. Cada canción de la versión de Wii U, incluido el DLC, hace un regreso glorioso
            Además, los Inklings aparecen como personajes invitados completamente nuevos, junto con los favoritos que regresan, como King Boo, Dry Bones y Bowser Jr.
            Los jugadores pueden elegir una nueva función de dirección inteligente que hace que conducir y permanecer en la pista sea fácil para jugadores novatos y niños, incluso a 200 cc',59.90,'assets/juegos-switch/mariokart8.webp','Switch','mariokart');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Mario Odyssey','Descripción del producto Explora reinos 3D llenos de secretos y sorpresas, incluyendo disfraces para Mario y varias formas de interactuar con los ambientes
            El nuevo amigo de Mario, Cappy, te permite dominar nuevos movimientos como lanzamiento de gorra, salto de gorra y captura
            Visita nuevos y sorprendentes lugares, como la ciudad Nueva Donk llena de rascacielos, y encuentra amigos y enemigos familiares mientras intentas salvar a la princesa Peach de las garras de Bowser y frustrar sus planes de boda malvados
            Entregue un controlador Joy-Con a un amigo para disfrutar del modo multijugador simultáneo: el jugador 1 controla a Mario mientras que el jugador 2 controla al nuevo aliado de Mario, Cappy
            Desbloquea aún más características con las nuevas y exclusivas figuras amiibo: Mario, Princesa Peach y Bowser vestidos con sus trajes de novia',50.90,'assets/juegos-switch/marioodyssey.webp','Switch','marioodyssey');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Mario Party Jamboree','Descripción del producto Únete a un jamboree de más de 110 minijuegos y 22 personajes jugables ¡La mayor cantidad de cualquier juego de Mario Party hasta la fecha!
            Siete tableros para jugar Incluyendo cinco nuevos como Goomba Lagoon y Rainbow Galleria.
            Dos tableros clásicos están de vuelta en Western Land y Carrera a través de minijuegos de ritmo rápido entre hasta 20 jugadores en línea en Koopathlon, o enfréntate a un Impostor Bowser en el Bowser Kaboom Squad en línea de 8 jugadores Una gran cantidad de modos adicionales, incluidos los de control de movimiento como Rhythm Kitchen, Toad''s Item Factory y Paratroopa Flight School. Castillo Arco Iris de Mario.
            Fiesta con amigos en nosotros. Puedes recibir una membresía individual en línea de Nintendo Switch de 3 meses si reservas o compras el juego antes del 31 de marzo de 2025, a las 11:59 pm PT, o ha',59.90,'assets/juegos-switch/marioparty.webp','Switch','marioparty');
INSERT INTO juegos (nombre,descripcion,precio,imagen,categoria,slug) VALUES ('Breath of The Wild','Descripción del producto Adéntrate en un mundo de descubrimiento, exploración y aventura en The Legend of Zelda: Breath of the Wild
            Explora un mundo de tamaño sin precedentes y descubre más de 100 santuarios llenos de rompecabezas, además de una amplia variedad de armas, trajes y equipo
            Sube por torres y picos de las montañas en busca de destinos, luego establece tu propio camino para llegar allí y sumergirte en el desierto; en el camino, lucharás contra imponentes enemigos, cazarás bestias salvajes y recolectarás ingredientes para la comida y elixires que necesitarás para mantenerte en tu viaje
            Los santuarios salpican el paisaje, esperando ser descubiertos en el orden que desee; búsquelos de varias maneras y resuelva una variedad de rompecabezas en el interior; abrirse camino a través de las trampas y dispositivos en el interior para ganar artículo',59.90,'assets/juegos-switch/zelda.webp','Switch','zelda');
